/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import java.util.*;
import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AAtributoExp extends PExp
{
    private final LinkedList<TId> _acessos_ = new LinkedList<TId>();
    private TId _nome_;

    public AAtributoExp()
    {
        // Constructor
    }

    public AAtributoExp(
        @SuppressWarnings("hiding") List<?> _acessos_,
        @SuppressWarnings("hiding") TId _nome_)
    {
        // Constructor
        setAcessos(_acessos_);

        setNome(_nome_);

    }

    @Override
    public Object clone()
    {
        return new AAtributoExp(
            cloneList(this._acessos_),
            cloneNode(this._nome_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAtributoExp(this);
    }

    public LinkedList<TId> getAcessos()
    {
        return this._acessos_;
    }

    public void setAcessos(List<?> list)
    {
        for(TId e : this._acessos_)
        {
            e.parent(null);
        }
        this._acessos_.clear();

        for(Object obj_e : list)
        {
            TId e = (TId) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._acessos_.add(e);
        }
    }

    public TId getNome()
    {
        return this._nome_;
    }

    public void setNome(TId node)
    {
        if(this._nome_ != null)
        {
            this._nome_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nome_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._acessos_)
            + toString(this._nome_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._acessos_.remove(child))
        {
            return;
        }

        if(this._nome_ == child)
        {
            this._nome_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<TId> i = this._acessos_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((TId) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._nome_ == oldChild)
        {
            setNome((TId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
