/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ABlocoComando extends PComando
{
    private PBlocoCmd _blocoCmd_;

    public ABlocoComando()
    {
        // Constructor
    }

    public ABlocoComando(
        @SuppressWarnings("hiding") PBlocoCmd _blocoCmd_)
    {
        // Constructor
        setBlocoCmd(_blocoCmd_);

    }

    @Override
    public Object clone()
    {
        return new ABlocoComando(
            cloneNode(this._blocoCmd_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABlocoComando(this);
    }

    public PBlocoCmd getBlocoCmd()
    {
        return this._blocoCmd_;
    }

    public void setBlocoCmd(PBlocoCmd node)
    {
        if(this._blocoCmd_ != null)
        {
            this._blocoCmd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._blocoCmd_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._blocoCmd_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._blocoCmd_ == child)
        {
            this._blocoCmd_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._blocoCmd_ == oldChild)
        {
            setBlocoCmd((PBlocoCmd) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
