/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import java.util.*;
import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ABlocoExpBlocoExp extends PBlocoExp
{
    private final LinkedList<PAtributosAlt> _atributos_ = new LinkedList<PAtributosAlt>();
    private PExp _valor_;

    public ABlocoExpBlocoExp()
    {
        // Constructor
    }

    public ABlocoExpBlocoExp(
        @SuppressWarnings("hiding") List<?> _atributos_,
        @SuppressWarnings("hiding") PExp _valor_)
    {
        // Constructor
        setAtributos(_atributos_);

        setValor(_valor_);

    }

    @Override
    public Object clone()
    {
        return new ABlocoExpBlocoExp(
            cloneList(this._atributos_),
            cloneNode(this._valor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABlocoExpBlocoExp(this);
    }

    public LinkedList<PAtributosAlt> getAtributos()
    {
        return this._atributos_;
    }

    public void setAtributos(List<?> list)
    {
        for(PAtributosAlt e : this._atributos_)
        {
            e.parent(null);
        }
        this._atributos_.clear();

        for(Object obj_e : list)
        {
            PAtributosAlt e = (PAtributosAlt) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._atributos_.add(e);
        }
    }

    public PExp getValor()
    {
        return this._valor_;
    }

    public void setValor(PExp node)
    {
        if(this._valor_ != null)
        {
            this._valor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._atributos_)
            + toString(this._valor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._atributos_.remove(child))
        {
            return;
        }

        if(this._valor_ == child)
        {
            this._valor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PAtributosAlt> i = this._atributos_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAtributosAlt) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._valor_ == oldChild)
        {
            setValor((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
