/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import java.util.*;
import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AChamadaChamada extends PChamada
{
    private final LinkedList<TId> _acessos_ = new LinkedList<TId>();
    private TId _nome_;
    private final LinkedList<PExp> _args_ = new LinkedList<PExp>();

    public AChamadaChamada()
    {
        // Constructor
    }

    public AChamadaChamada(
        @SuppressWarnings("hiding") List<?> _acessos_,
        @SuppressWarnings("hiding") TId _nome_,
        @SuppressWarnings("hiding") List<?> _args_)
    {
        // Constructor
        setAcessos(_acessos_);

        setNome(_nome_);

        setArgs(_args_);

    }

    @Override
    public Object clone()
    {
        return new AChamadaChamada(
            cloneList(this._acessos_),
            cloneNode(this._nome_),
            cloneList(this._args_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAChamadaChamada(this);
    }

    public LinkedList<TId> getAcessos()
    {
        return this._acessos_;
    }

    public void setAcessos(List<?> list)
    {
        for(TId e : this._acessos_)
        {
            e.parent(null);
        }
        this._acessos_.clear();

        for(Object obj_e : list)
        {
            TId e = (TId) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._acessos_.add(e);
        }
    }

    public TId getNome()
    {
        return this._nome_;
    }

    public void setNome(TId node)
    {
        if(this._nome_ != null)
        {
            this._nome_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nome_ = node;
    }

    public LinkedList<PExp> getArgs()
    {
        return this._args_;
    }

    public void setArgs(List<?> list)
    {
        for(PExp e : this._args_)
        {
            e.parent(null);
        }
        this._args_.clear();

        for(Object obj_e : list)
        {
            PExp e = (PExp) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._args_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._acessos_)
            + toString(this._nome_)
            + toString(this._args_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._acessos_.remove(child))
        {
            return;
        }

        if(this._nome_ == child)
        {
            this._nome_ = null;
            return;
        }

        if(this._args_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<TId> i = this._acessos_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((TId) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._nome_ == oldChild)
        {
            setNome((TId) newChild);
            return;
        }

        for(ListIterator<PExp> i = this._args_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExp) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
