/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import java.util.*;
import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ADefClasseDefClasse extends PDefClasse
{
    private PTipoClasse _tipoClasse_;
    private final LinkedList<PAtributosAlt> _atributos_ = new LinkedList<PAtributosAlt>();
    private final LinkedList<PMetodosAlt> _metodos_ = new LinkedList<PMetodosAlt>();

    public ADefClasseDefClasse()
    {
        // Constructor
    }

    public ADefClasseDefClasse(
        @SuppressWarnings("hiding") PTipoClasse _tipoClasse_,
        @SuppressWarnings("hiding") List<?> _atributos_,
        @SuppressWarnings("hiding") List<?> _metodos_)
    {
        // Constructor
        setTipoClasse(_tipoClasse_);

        setAtributos(_atributos_);

        setMetodos(_metodos_);

    }

    @Override
    public Object clone()
    {
        return new ADefClasseDefClasse(
            cloneNode(this._tipoClasse_),
            cloneList(this._atributos_),
            cloneList(this._metodos_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADefClasseDefClasse(this);
    }

    public PTipoClasse getTipoClasse()
    {
        return this._tipoClasse_;
    }

    public void setTipoClasse(PTipoClasse node)
    {
        if(this._tipoClasse_ != null)
        {
            this._tipoClasse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoClasse_ = node;
    }

    public LinkedList<PAtributosAlt> getAtributos()
    {
        return this._atributos_;
    }

    public void setAtributos(List<?> list)
    {
        for(PAtributosAlt e : this._atributos_)
        {
            e.parent(null);
        }
        this._atributos_.clear();

        for(Object obj_e : list)
        {
            PAtributosAlt e = (PAtributosAlt) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._atributos_.add(e);
        }
    }

    public LinkedList<PMetodosAlt> getMetodos()
    {
        return this._metodos_;
    }

    public void setMetodos(List<?> list)
    {
        for(PMetodosAlt e : this._metodos_)
        {
            e.parent(null);
        }
        this._metodos_.clear();

        for(Object obj_e : list)
        {
            PMetodosAlt e = (PMetodosAlt) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._metodos_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipoClasse_)
            + toString(this._atributos_)
            + toString(this._metodos_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipoClasse_ == child)
        {
            this._tipoClasse_ = null;
            return;
        }

        if(this._atributos_.remove(child))
        {
            return;
        }

        if(this._metodos_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipoClasse_ == oldChild)
        {
            setTipoClasse((PTipoClasse) newChild);
            return;
        }

        for(ListIterator<PAtributosAlt> i = this._atributos_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAtributosAlt) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator<PMetodosAlt> i = this._metodos_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PMetodosAlt) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
