/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AFuncaoMetodosAlt extends PMetodosAlt
{
    private PFunctionHeader _header_;
    private PBlocoExp _corpo_;

    public AFuncaoMetodosAlt()
    {
        // Constructor
    }

    public AFuncaoMetodosAlt(
        @SuppressWarnings("hiding") PFunctionHeader _header_,
        @SuppressWarnings("hiding") PBlocoExp _corpo_)
    {
        // Constructor
        setHeader(_header_);

        setCorpo(_corpo_);

    }

    @Override
    public Object clone()
    {
        return new AFuncaoMetodosAlt(
            cloneNode(this._header_),
            cloneNode(this._corpo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFuncaoMetodosAlt(this);
    }

    public PFunctionHeader getHeader()
    {
        return this._header_;
    }

    public void setHeader(PFunctionHeader node)
    {
        if(this._header_ != null)
        {
            this._header_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._header_ = node;
    }

    public PBlocoExp getCorpo()
    {
        return this._corpo_;
    }

    public void setCorpo(PBlocoExp node)
    {
        if(this._corpo_ != null)
        {
            this._corpo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._corpo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._header_)
            + toString(this._corpo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._header_ == child)
        {
            this._header_ = null;
            return;
        }

        if(this._corpo_ == child)
        {
            this._corpo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._header_ == oldChild)
        {
            setHeader((PFunctionHeader) newChild);
            return;
        }

        if(this._corpo_ == oldChild)
        {
            setCorpo((PBlocoExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
