/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AIfComando extends PComando
{
    private PExp _cond_;
    private PComando _verdadeiro_;
    private PComando _falso_;

    public AIfComando()
    {
        // Constructor
    }

    public AIfComando(
        @SuppressWarnings("hiding") PExp _cond_,
        @SuppressWarnings("hiding") PComando _verdadeiro_,
        @SuppressWarnings("hiding") PComando _falso_)
    {
        // Constructor
        setCond(_cond_);

        setVerdadeiro(_verdadeiro_);

        setFalso(_falso_);

    }

    @Override
    public Object clone()
    {
        return new AIfComando(
            cloneNode(this._cond_),
            cloneNode(this._verdadeiro_),
            cloneNode(this._falso_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfComando(this);
    }

    public PExp getCond()
    {
        return this._cond_;
    }

    public void setCond(PExp node)
    {
        if(this._cond_ != null)
        {
            this._cond_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cond_ = node;
    }

    public PComando getVerdadeiro()
    {
        return this._verdadeiro_;
    }

    public void setVerdadeiro(PComando node)
    {
        if(this._verdadeiro_ != null)
        {
            this._verdadeiro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._verdadeiro_ = node;
    }

    public PComando getFalso()
    {
        return this._falso_;
    }

    public void setFalso(PComando node)
    {
        if(this._falso_ != null)
        {
            this._falso_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._falso_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cond_)
            + toString(this._verdadeiro_)
            + toString(this._falso_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cond_ == child)
        {
            this._cond_ = null;
            return;
        }

        if(this._verdadeiro_ == child)
        {
            this._verdadeiro_ = null;
            return;
        }

        if(this._falso_ == child)
        {
            this._falso_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cond_ == oldChild)
        {
            setCond((PExp) newChild);
            return;
        }

        if(this._verdadeiro_ == oldChild)
        {
            setVerdadeiro((PComando) newChild);
            return;
        }

        if(this._falso_ == oldChild)
        {
            setFalso((PComando) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
