/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ANotExp extends PExp
{
    private PExp _operando_;

    public ANotExp()
    {
        // Constructor
    }

    public ANotExp(
        @SuppressWarnings("hiding") PExp _operando_)
    {
        // Constructor
        setOperando(_operando_);

    }

    @Override
    public Object clone()
    {
        return new ANotExp(
            cloneNode(this._operando_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotExp(this);
    }

    public PExp getOperando()
    {
        return this._operando_;
    }

    public void setOperando(PExp node)
    {
        if(this._operando_ != null)
        {
            this._operando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._operando_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._operando_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._operando_ == child)
        {
            this._operando_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._operando_ == oldChild)
        {
            setOperando((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
