/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AObjetoAtributosAlt extends PAtributosAlt
{
    private PTipoClasse _tipoClasse_;
    private TId _id_;

    public AObjetoAtributosAlt()
    {
        // Constructor
    }

    public AObjetoAtributosAlt(
        @SuppressWarnings("hiding") PTipoClasse _tipoClasse_,
        @SuppressWarnings("hiding") TId _id_)
    {
        // Constructor
        setTipoClasse(_tipoClasse_);

        setId(_id_);

    }

    @Override
    public Object clone()
    {
        return new AObjetoAtributosAlt(
            cloneNode(this._tipoClasse_),
            cloneNode(this._id_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAObjetoAtributosAlt(this);
    }

    public PTipoClasse getTipoClasse()
    {
        return this._tipoClasse_;
    }

    public void setTipoClasse(PTipoClasse node)
    {
        if(this._tipoClasse_ != null)
        {
            this._tipoClasse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoClasse_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipoClasse_)
            + toString(this._id_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipoClasse_ == child)
        {
            this._tipoClasse_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipoClasse_ == oldChild)
        {
            setTipoClasse((PTipoClasse) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
