/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import java.util.*;
import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AProgramaPrograma extends PPrograma
{
    private final LinkedList<PRelacao> _relacoes_ = new LinkedList<PRelacao>();
    private final LinkedList<PDefClasse> _classes_ = new LinkedList<PDefClasse>();

    public AProgramaPrograma()
    {
        // Constructor
    }

    public AProgramaPrograma(
        @SuppressWarnings("hiding") List<?> _relacoes_,
        @SuppressWarnings("hiding") List<?> _classes_)
    {
        // Constructor
        setRelacoes(_relacoes_);

        setClasses(_classes_);

    }

    @Override
    public Object clone()
    {
        return new AProgramaPrograma(
            cloneList(this._relacoes_),
            cloneList(this._classes_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProgramaPrograma(this);
    }

    public LinkedList<PRelacao> getRelacoes()
    {
        return this._relacoes_;
    }

    public void setRelacoes(List<?> list)
    {
        for(PRelacao e : this._relacoes_)
        {
            e.parent(null);
        }
        this._relacoes_.clear();

        for(Object obj_e : list)
        {
            PRelacao e = (PRelacao) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._relacoes_.add(e);
        }
    }

    public LinkedList<PDefClasse> getClasses()
    {
        return this._classes_;
    }

    public void setClasses(List<?> list)
    {
        for(PDefClasse e : this._classes_)
        {
            e.parent(null);
        }
        this._classes_.clear();

        for(Object obj_e : list)
        {
            PDefClasse e = (PDefClasse) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._classes_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._relacoes_)
            + toString(this._classes_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._relacoes_.remove(child))
        {
            return;
        }

        if(this._classes_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PRelacao> i = this._relacoes_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PRelacao) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator<PDefClasse> i = this._classes_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDefClasse) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
