/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AProcedimentoMetodosAlt extends PMetodosAlt
{
    private TOpEntry _opEntry_;
    private PProcedureHeader _header_;
    private PBlocoCmd _corpo_;

    public AProcedimentoMetodosAlt()
    {
        // Constructor
    }

    public AProcedimentoMetodosAlt(
        @SuppressWarnings("hiding") TOpEntry _opEntry_,
        @SuppressWarnings("hiding") PProcedureHeader _header_,
        @SuppressWarnings("hiding") PBlocoCmd _corpo_)
    {
        // Constructor
        setOpEntry(_opEntry_);

        setHeader(_header_);

        setCorpo(_corpo_);

    }

    @Override
    public Object clone()
    {
        return new AProcedimentoMetodosAlt(
            cloneNode(this._opEntry_),
            cloneNode(this._header_),
            cloneNode(this._corpo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProcedimentoMetodosAlt(this);
    }

    public TOpEntry getOpEntry()
    {
        return this._opEntry_;
    }

    public void setOpEntry(TOpEntry node)
    {
        if(this._opEntry_ != null)
        {
            this._opEntry_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opEntry_ = node;
    }

    public PProcedureHeader getHeader()
    {
        return this._header_;
    }

    public void setHeader(PProcedureHeader node)
    {
        if(this._header_ != null)
        {
            this._header_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._header_ = node;
    }

    public PBlocoCmd getCorpo()
    {
        return this._corpo_;
    }

    public void setCorpo(PBlocoCmd node)
    {
        if(this._corpo_ != null)
        {
            this._corpo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._corpo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._opEntry_)
            + toString(this._header_)
            + toString(this._corpo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._opEntry_ == child)
        {
            this._opEntry_ = null;
            return;
        }

        if(this._header_ == child)
        {
            this._header_ = null;
            return;
        }

        if(this._corpo_ == child)
        {
            this._corpo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._opEntry_ == oldChild)
        {
            setOpEntry((TOpEntry) newChild);
            return;
        }

        if(this._header_ == oldChild)
        {
            setHeader((PProcedureHeader) newChild);
            return;
        }

        if(this._corpo_ == oldChild)
        {
            setCorpo((PBlocoCmd) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
