/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ARelacaoRelacao extends PRelacao
{
    private PTipoClasse _filho_;
    private PTipoClasse _pai_;

    public ARelacaoRelacao()
    {
        // Constructor
    }

    public ARelacaoRelacao(
        @SuppressWarnings("hiding") PTipoClasse _filho_,
        @SuppressWarnings("hiding") PTipoClasse _pai_)
    {
        // Constructor
        setFilho(_filho_);

        setPai(_pai_);

    }

    @Override
    public Object clone()
    {
        return new ARelacaoRelacao(
            cloneNode(this._filho_),
            cloneNode(this._pai_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARelacaoRelacao(this);
    }

    public PTipoClasse getFilho()
    {
        return this._filho_;
    }

    public void setFilho(PTipoClasse node)
    {
        if(this._filho_ != null)
        {
            this._filho_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._filho_ = node;
    }

    public PTipoClasse getPai()
    {
        return this._pai_;
    }

    public void setPai(PTipoClasse node)
    {
        if(this._pai_ != null)
        {
            this._pai_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pai_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._filho_)
            + toString(this._pai_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._filho_ == child)
        {
            this._filho_ = null;
            return;
        }

        if(this._pai_ == child)
        {
            this._pai_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._filho_ == oldChild)
        {
            setFilho((PTipoClasse) newChild);
            return;
        }

        if(this._pai_ == oldChild)
        {
            setPai((PTipoClasse) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
