/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TKwAnswer extends Token
{
    public TKwAnswer()
    {
        super.setText("answer");
    }

    public TKwAnswer(int line, int pos)
    {
        super.setText("answer");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwAnswer(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwAnswer(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwAnswer text.");
    }
}
