/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TKwCase extends Token
{
    public TKwCase()
    {
        super.setText("case");
    }

    public TKwCase(int line, int pos)
    {
        super.setText("case");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwCase(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwCase(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwCase text.");
    }
}
