/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TKwDerives extends Token
{
    public TKwDerives()
    {
        super.setText("derives");
    }

    public TKwDerives(int line, int pos)
    {
        super.setText("derives");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwDerives(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwDerives(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwDerives text.");
    }
}
