/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TKwFamily extends Token
{
    public TKwFamily()
    {
        super.setText("family");
    }

    public TKwFamily(int line, int pos)
    {
        super.setText("family");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwFamily(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwFamily(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwFamily text.");
    }
}
