/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TKwFrom extends Token
{
    public TKwFrom()
    {
        super.setText("from");
    }

    public TKwFrom(int line, int pos)
    {
        super.setText("from");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwFrom(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwFrom(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwFrom text.");
    }
}
