/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TKwNumber extends Token
{
    public TKwNumber()
    {
        super.setText("number");
    }

    public TKwNumber(int line, int pos)
    {
        super.setText("number");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwNumber(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwNumber(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwNumber text.");
    }
}
