/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TKwOtherwise extends Token
{
    public TKwOtherwise()
    {
        super.setText("otherwise");
    }

    public TKwOtherwise(int line, int pos)
    {
        super.setText("otherwise");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwOtherwise(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwOtherwise(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwOtherwise text.");
    }
}
