/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TKwObject extends Token
{
    public TKwObject()
    {
        super.setText("object");
    }

    public TKwObject(int line, int pos)
    {
        super.setText("object");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwObject(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwObject(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwObject text.");
    }
}
