/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TKwProcedure extends Token
{
    public TKwProcedure()
    {
        super.setText("procedure");
    }

    public TKwProcedure(int line, int pos)
    {
        super.setText("procedure");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwProcedure(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwProcedure(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwProcedure text.");
    }
}
