/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TKwStart extends Token
{
    public TKwStart()
    {
        super.setText("start");
    }

    public TKwStart(int line, int pos)
    {
        super.setText("start");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwStart(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwStart(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwStart text.");
    }
}
