/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TKwThat extends Token
{
    public TKwThat()
    {
        super.setText("that");
    }

    public TKwThat(int line, int pos)
    {
        super.setText("that");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwThat(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwThat(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwThat text.");
    }
}
