/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TKwUnalterable extends Token
{
    public TKwUnalterable()
    {
        super.setText("unalterable");
    }

    public TKwUnalterable(int line, int pos)
    {
        super.setText("unalterable");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwUnalterable(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwUnalterable(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwUnalterable text.");
    }
}
