/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TValorNo extends Token
{
    public TValorNo()
    {
        super.setText("no");
    }

    public TValorNo(int line, int pos)
    {
        super.setText("no");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TValorNo(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTValorNo(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TValorNo text.");
    }
}
