/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TValorYes extends Token
{
    public TValorYes()
    {
        super.setText("yes");
    }

    public TValorYes(int line, int pos)
    {
        super.setText("yes");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TValorYes(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTValorYes(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TValorYes text.");
    }
}
