/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.analysis;

import java.util.*;
import dplusplus.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    @Override
    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    @Override
    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    @Override
    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    @Override
    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    @Override
    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAProgramaPrograma(AProgramaPrograma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARelacaoRelacao(ARelacaoRelacao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADefClasseDefClasse(ADefClasseDefClasse node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAObjetoAtributosAlt(AObjetoAtributosAlt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVariavelAtributosAlt(AVariavelAtributosAlt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAConstanteAtributosAlt(AConstanteAtributosAlt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAProcedureHeaderProcedureHeader(AProcedureHeaderProcedureHeader node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFunctionHeaderFunctionHeader(AFunctionHeaderFunctionHeader node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAProcedimentoMetodosAlt(AProcedimentoMetodosAlt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFuncaoMetodosAlt(AFuncaoMetodosAlt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParametroParametro(AParametroParametro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAClasseTipo(AClasseTipo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPrimitivoTipo(APrimitivoTipo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATipoClasseTipoClasse(ATipoClasseTipoClasse node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAnswerTipoPrimitivo(AAnswerTipoPrimitivo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANumberTipoPrimitivo(ANumberTipoPrimitivo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIfComando(AIfComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAWhileComando(AWhileComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAtribuicaoComando(AAtribuicaoComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAChamadaComando(AChamadaComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABlocoComando(ABlocoComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABlocoCmdBlocoCmd(ABlocoCmdBlocoCmd node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAChamadaChamada(AChamadaChamada node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATernarioExp(ATernarioExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAOrExp(AOrExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAndExp(AAndExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEqExp(AEqExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALtExp(ALtExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAGtExp(AGtExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPlusExp(APlusExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMinusExp(AMinusExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMultExp(AMultExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADivExp(ADivExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANegExp(ANegExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANotExp(ANotExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARealExp(ARealExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInteiroExp(AInteiroExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAYesExp(AYesExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANoExp(ANoExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAChamadaExp(AChamadaExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAtributoExp(AAtributoExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABlocoExp(ABlocoExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABlocoExpBlocoExp(ABlocoExpBlocoExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBlank(TBlank node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTLineComment(TTLineComment node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTBlockComment(TTBlockComment node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTKwFamily(TKwFamily node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTKwDerives(TKwDerives node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTKwFrom(TKwFrom node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTKwStart(TKwStart node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTKwFinish(TKwFinish node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTKwObject(TKwObject node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTKwAlterable(TKwAlterable node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTKwUnalterable(TKwUnalterable node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTKwAnswer(TKwAnswer node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTKwNumber(TKwNumber node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTValorYes(TValorYes node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTValorNo(TValorNo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTKwProcedure(TKwProcedure node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTKwFunction(TKwFunction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTKwIn(TKwIn node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTKwCase(TKwCase node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTKwThat(TKwThat node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTKwOtherwise(TKwOtherwise node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTKwAs(TKwAs node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTKwLong(TKwLong node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTKwIf(TKwIf node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTKwElse(TKwElse node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTValorReal(TValorReal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTValorInteiro(TValorInteiro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOpAssign(TOpAssign node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOpEntry(TOpEntry node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOpPlus(TOpPlus node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOpMinus(TOpMinus node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOpMult(TOpMult node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOpDiv(TOpDiv node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOpEq(TOpEq node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOpLt(TOpLt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOpGt(TOpGt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOpAnd(TOpAnd node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOpOr(TOpOr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOpNot(TOpNot node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLBracket(TLBracket node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRBracket(TRBracket node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLPar(TLPar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRPar(TRPar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDot(TDot node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPipe(TPipe node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAmp(TAmp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSeta(TSeta node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIdClasse(TIdClasse node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTId(TId node)
    {
        defaultCase(node);
    }

    @Override
    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    @Override
    public void caseInvalidToken(InvalidToken node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
