/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.analysis;

import java.util.*;
import dplusplus.node.*;

public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPPrograma().apply(this);
        outStart(node);
    }

    public void inAProgramaPrograma(AProgramaPrograma node)
    {
        defaultIn(node);
    }

    public void outAProgramaPrograma(AProgramaPrograma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAProgramaPrograma(AProgramaPrograma node)
    {
        inAProgramaPrograma(node);
        {
            List<PDefClasse> copy = new ArrayList<PDefClasse>(node.getClasses());
            Collections.reverse(copy);
            for(PDefClasse e : copy)
            {
                e.apply(this);
            }
        }
        {
            List<PRelacao> copy = new ArrayList<PRelacao>(node.getRelacoes());
            Collections.reverse(copy);
            for(PRelacao e : copy)
            {
                e.apply(this);
            }
        }
        outAProgramaPrograma(node);
    }

    public void inARelacaoRelacao(ARelacaoRelacao node)
    {
        defaultIn(node);
    }

    public void outARelacaoRelacao(ARelacaoRelacao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARelacaoRelacao(ARelacaoRelacao node)
    {
        inARelacaoRelacao(node);
        if(node.getPai() != null)
        {
            node.getPai().apply(this);
        }
        if(node.getFilho() != null)
        {
            node.getFilho().apply(this);
        }
        outARelacaoRelacao(node);
    }

    public void inADefClasseDefClasse(ADefClasseDefClasse node)
    {
        defaultIn(node);
    }

    public void outADefClasseDefClasse(ADefClasseDefClasse node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADefClasseDefClasse(ADefClasseDefClasse node)
    {
        inADefClasseDefClasse(node);
        {
            List<PMetodosAlt> copy = new ArrayList<PMetodosAlt>(node.getMetodos());
            Collections.reverse(copy);
            for(PMetodosAlt e : copy)
            {
                e.apply(this);
            }
        }
        {
            List<PAtributosAlt> copy = new ArrayList<PAtributosAlt>(node.getAtributos());
            Collections.reverse(copy);
            for(PAtributosAlt e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getTipoClasse() != null)
        {
            node.getTipoClasse().apply(this);
        }
        outADefClasseDefClasse(node);
    }

    public void inAObjetoAtributosAlt(AObjetoAtributosAlt node)
    {
        defaultIn(node);
    }

    public void outAObjetoAtributosAlt(AObjetoAtributosAlt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAObjetoAtributosAlt(AObjetoAtributosAlt node)
    {
        inAObjetoAtributosAlt(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getTipoClasse() != null)
        {
            node.getTipoClasse().apply(this);
        }
        outAObjetoAtributosAlt(node);
    }

    public void inAVariavelAtributosAlt(AVariavelAtributosAlt node)
    {
        defaultIn(node);
    }

    public void outAVariavelAtributosAlt(AVariavelAtributosAlt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVariavelAtributosAlt(AVariavelAtributosAlt node)
    {
        inAVariavelAtributosAlt(node);
        if(node.getValor() != null)
        {
            node.getValor().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getTipoPrimitivo() != null)
        {
            node.getTipoPrimitivo().apply(this);
        }
        outAVariavelAtributosAlt(node);
    }

    public void inAConstanteAtributosAlt(AConstanteAtributosAlt node)
    {
        defaultIn(node);
    }

    public void outAConstanteAtributosAlt(AConstanteAtributosAlt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAConstanteAtributosAlt(AConstanteAtributosAlt node)
    {
        inAConstanteAtributosAlt(node);
        if(node.getValor() != null)
        {
            node.getValor().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getTipoPrimitivo() != null)
        {
            node.getTipoPrimitivo().apply(this);
        }
        outAConstanteAtributosAlt(node);
    }

    public void inAProcedureHeaderProcedureHeader(AProcedureHeaderProcedureHeader node)
    {
        defaultIn(node);
    }

    public void outAProcedureHeaderProcedureHeader(AProcedureHeaderProcedureHeader node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAProcedureHeaderProcedureHeader(AProcedureHeaderProcedureHeader node)
    {
        inAProcedureHeaderProcedureHeader(node);
        {
            List<PParametro> copy = new ArrayList<PParametro>(node.getParams());
            Collections.reverse(copy);
            for(PParametro e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAProcedureHeaderProcedureHeader(node);
    }

    public void inAFunctionHeaderFunctionHeader(AFunctionHeaderFunctionHeader node)
    {
        defaultIn(node);
    }

    public void outAFunctionHeaderFunctionHeader(AFunctionHeaderFunctionHeader node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFunctionHeaderFunctionHeader(AFunctionHeaderFunctionHeader node)
    {
        inAFunctionHeaderFunctionHeader(node);
        {
            List<PParametro> copy = new ArrayList<PParametro>(node.getParams());
            Collections.reverse(copy);
            for(PParametro e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        outAFunctionHeaderFunctionHeader(node);
    }

    public void inAProcedimentoMetodosAlt(AProcedimentoMetodosAlt node)
    {
        defaultIn(node);
    }

    public void outAProcedimentoMetodosAlt(AProcedimentoMetodosAlt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAProcedimentoMetodosAlt(AProcedimentoMetodosAlt node)
    {
        inAProcedimentoMetodosAlt(node);
        if(node.getCorpo() != null)
        {
            node.getCorpo().apply(this);
        }
        if(node.getHeader() != null)
        {
            node.getHeader().apply(this);
        }
        if(node.getOpEntry() != null)
        {
            node.getOpEntry().apply(this);
        }
        outAProcedimentoMetodosAlt(node);
    }

    public void inAFuncaoMetodosAlt(AFuncaoMetodosAlt node)
    {
        defaultIn(node);
    }

    public void outAFuncaoMetodosAlt(AFuncaoMetodosAlt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFuncaoMetodosAlt(AFuncaoMetodosAlt node)
    {
        inAFuncaoMetodosAlt(node);
        if(node.getCorpo() != null)
        {
            node.getCorpo().apply(this);
        }
        if(node.getHeader() != null)
        {
            node.getHeader().apply(this);
        }
        outAFuncaoMetodosAlt(node);
    }

    public void inAParametroParametro(AParametroParametro node)
    {
        defaultIn(node);
    }

    public void outAParametroParametro(AParametroParametro node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParametroParametro(AParametroParametro node)
    {
        inAParametroParametro(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        outAParametroParametro(node);
    }

    public void inAClasseTipo(AClasseTipo node)
    {
        defaultIn(node);
    }

    public void outAClasseTipo(AClasseTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAClasseTipo(AClasseTipo node)
    {
        inAClasseTipo(node);
        if(node.getTipoClasse() != null)
        {
            node.getTipoClasse().apply(this);
        }
        outAClasseTipo(node);
    }

    public void inAPrimitivoTipo(APrimitivoTipo node)
    {
        defaultIn(node);
    }

    public void outAPrimitivoTipo(APrimitivoTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrimitivoTipo(APrimitivoTipo node)
    {
        inAPrimitivoTipo(node);
        if(node.getTipoPrimitivo() != null)
        {
            node.getTipoPrimitivo().apply(this);
        }
        outAPrimitivoTipo(node);
    }

    public void inATipoClasseTipoClasse(ATipoClasseTipoClasse node)
    {
        defaultIn(node);
    }

    public void outATipoClasseTipoClasse(ATipoClasseTipoClasse node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATipoClasseTipoClasse(ATipoClasseTipoClasse node)
    {
        inATipoClasseTipoClasse(node);
        if(node.getIdClasse() != null)
        {
            node.getIdClasse().apply(this);
        }
        outATipoClasseTipoClasse(node);
    }

    public void inAAnswerTipoPrimitivo(AAnswerTipoPrimitivo node)
    {
        defaultIn(node);
    }

    public void outAAnswerTipoPrimitivo(AAnswerTipoPrimitivo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAnswerTipoPrimitivo(AAnswerTipoPrimitivo node)
    {
        inAAnswerTipoPrimitivo(node);
        outAAnswerTipoPrimitivo(node);
    }

    public void inANumberTipoPrimitivo(ANumberTipoPrimitivo node)
    {
        defaultIn(node);
    }

    public void outANumberTipoPrimitivo(ANumberTipoPrimitivo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANumberTipoPrimitivo(ANumberTipoPrimitivo node)
    {
        inANumberTipoPrimitivo(node);
        outANumberTipoPrimitivo(node);
    }

    public void inAIfComando(AIfComando node)
    {
        defaultIn(node);
    }

    public void outAIfComando(AIfComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIfComando(AIfComando node)
    {
        inAIfComando(node);
        if(node.getFalso() != null)
        {
            node.getFalso().apply(this);
        }
        if(node.getVerdadeiro() != null)
        {
            node.getVerdadeiro().apply(this);
        }
        if(node.getCond() != null)
        {
            node.getCond().apply(this);
        }
        outAIfComando(node);
    }

    public void inAWhileComando(AWhileComando node)
    {
        defaultIn(node);
    }

    public void outAWhileComando(AWhileComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAWhileComando(AWhileComando node)
    {
        inAWhileComando(node);
        if(node.getCorpo() != null)
        {
            node.getCorpo().apply(this);
        }
        if(node.getCond() != null)
        {
            node.getCond().apply(this);
        }
        outAWhileComando(node);
    }

    public void inAAtribuicaoComando(AAtribuicaoComando node)
    {
        defaultIn(node);
    }

    public void outAAtribuicaoComando(AAtribuicaoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAtribuicaoComando(AAtribuicaoComando node)
    {
        inAAtribuicaoComando(node);
        if(node.getValor() != null)
        {
            node.getValor().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAAtribuicaoComando(node);
    }

    public void inAChamadaComando(AChamadaComando node)
    {
        defaultIn(node);
    }

    public void outAChamadaComando(AChamadaComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAChamadaComando(AChamadaComando node)
    {
        inAChamadaComando(node);
        if(node.getChamada() != null)
        {
            node.getChamada().apply(this);
        }
        outAChamadaComando(node);
    }

    public void inABlocoComando(ABlocoComando node)
    {
        defaultIn(node);
    }

    public void outABlocoComando(ABlocoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlocoComando(ABlocoComando node)
    {
        inABlocoComando(node);
        if(node.getBlocoCmd() != null)
        {
            node.getBlocoCmd().apply(this);
        }
        outABlocoComando(node);
    }

    public void inABlocoCmdBlocoCmd(ABlocoCmdBlocoCmd node)
    {
        defaultIn(node);
    }

    public void outABlocoCmdBlocoCmd(ABlocoCmdBlocoCmd node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlocoCmdBlocoCmd(ABlocoCmdBlocoCmd node)
    {
        inABlocoCmdBlocoCmd(node);
        {
            List<PComando> copy = new ArrayList<PComando>(node.getComandos());
            Collections.reverse(copy);
            for(PComando e : copy)
            {
                e.apply(this);
            }
        }
        {
            List<PAtributosAlt> copy = new ArrayList<PAtributosAlt>(node.getAtributos());
            Collections.reverse(copy);
            for(PAtributosAlt e : copy)
            {
                e.apply(this);
            }
        }
        outABlocoCmdBlocoCmd(node);
    }

    public void inAChamadaChamada(AChamadaChamada node)
    {
        defaultIn(node);
    }

    public void outAChamadaChamada(AChamadaChamada node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAChamadaChamada(AChamadaChamada node)
    {
        inAChamadaChamada(node);
        {
            List<PExp> copy = new ArrayList<PExp>(node.getArgs());
            Collections.reverse(copy);
            for(PExp e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getNome() != null)
        {
            node.getNome().apply(this);
        }
        {
            List<TId> copy = new ArrayList<TId>(node.getAcessos());
            Collections.reverse(copy);
            for(TId e : copy)
            {
                e.apply(this);
            }
        }
        outAChamadaChamada(node);
    }

    public void inATernarioExp(ATernarioExp node)
    {
        defaultIn(node);
    }

    public void outATernarioExp(ATernarioExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATernarioExp(ATernarioExp node)
    {
        inATernarioExp(node);
        if(node.getFalso() != null)
        {
            node.getFalso().apply(this);
        }
        if(node.getVerdadeiro() != null)
        {
            node.getVerdadeiro().apply(this);
        }
        if(node.getCond() != null)
        {
            node.getCond().apply(this);
        }
        outATernarioExp(node);
    }

    public void inAOrExp(AOrExp node)
    {
        defaultIn(node);
    }

    public void outAOrExp(AOrExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOrExp(AOrExp node)
    {
        inAOrExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outAOrExp(node);
    }

    public void inAAndExp(AAndExp node)
    {
        defaultIn(node);
    }

    public void outAAndExp(AAndExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAndExp(AAndExp node)
    {
        inAAndExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outAAndExp(node);
    }

    public void inAEqExp(AEqExp node)
    {
        defaultIn(node);
    }

    public void outAEqExp(AEqExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEqExp(AEqExp node)
    {
        inAEqExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outAEqExp(node);
    }

    public void inALtExp(ALtExp node)
    {
        defaultIn(node);
    }

    public void outALtExp(ALtExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALtExp(ALtExp node)
    {
        inALtExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outALtExp(node);
    }

    public void inAGtExp(AGtExp node)
    {
        defaultIn(node);
    }

    public void outAGtExp(AGtExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAGtExp(AGtExp node)
    {
        inAGtExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outAGtExp(node);
    }

    public void inAPlusExp(APlusExp node)
    {
        defaultIn(node);
    }

    public void outAPlusExp(APlusExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPlusExp(APlusExp node)
    {
        inAPlusExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outAPlusExp(node);
    }

    public void inAMinusExp(AMinusExp node)
    {
        defaultIn(node);
    }

    public void outAMinusExp(AMinusExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMinusExp(AMinusExp node)
    {
        inAMinusExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outAMinusExp(node);
    }

    public void inAMultExp(AMultExp node)
    {
        defaultIn(node);
    }

    public void outAMultExp(AMultExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultExp(AMultExp node)
    {
        inAMultExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outAMultExp(node);
    }

    public void inADivExp(ADivExp node)
    {
        defaultIn(node);
    }

    public void outADivExp(ADivExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADivExp(ADivExp node)
    {
        inADivExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outADivExp(node);
    }

    public void inANegExp(ANegExp node)
    {
        defaultIn(node);
    }

    public void outANegExp(ANegExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANegExp(ANegExp node)
    {
        inANegExp(node);
        if(node.getOperando() != null)
        {
            node.getOperando().apply(this);
        }
        outANegExp(node);
    }

    public void inANotExp(ANotExp node)
    {
        defaultIn(node);
    }

    public void outANotExp(ANotExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANotExp(ANotExp node)
    {
        inANotExp(node);
        if(node.getOperando() != null)
        {
            node.getOperando().apply(this);
        }
        outANotExp(node);
    }

    public void inARealExp(ARealExp node)
    {
        defaultIn(node);
    }

    public void outARealExp(ARealExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARealExp(ARealExp node)
    {
        inARealExp(node);
        if(node.getValorReal() != null)
        {
            node.getValorReal().apply(this);
        }
        outARealExp(node);
    }

    public void inAInteiroExp(AInteiroExp node)
    {
        defaultIn(node);
    }

    public void outAInteiroExp(AInteiroExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAInteiroExp(AInteiroExp node)
    {
        inAInteiroExp(node);
        if(node.getValorInteiro() != null)
        {
            node.getValorInteiro().apply(this);
        }
        outAInteiroExp(node);
    }

    public void inAYesExp(AYesExp node)
    {
        defaultIn(node);
    }

    public void outAYesExp(AYesExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAYesExp(AYesExp node)
    {
        inAYesExp(node);
        outAYesExp(node);
    }

    public void inANoExp(ANoExp node)
    {
        defaultIn(node);
    }

    public void outANoExp(ANoExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANoExp(ANoExp node)
    {
        inANoExp(node);
        outANoExp(node);
    }

    public void inAChamadaExp(AChamadaExp node)
    {
        defaultIn(node);
    }

    public void outAChamadaExp(AChamadaExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAChamadaExp(AChamadaExp node)
    {
        inAChamadaExp(node);
        if(node.getChamada() != null)
        {
            node.getChamada().apply(this);
        }
        outAChamadaExp(node);
    }

    public void inAAtributoExp(AAtributoExp node)
    {
        defaultIn(node);
    }

    public void outAAtributoExp(AAtributoExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAtributoExp(AAtributoExp node)
    {
        inAAtributoExp(node);
        if(node.getNome() != null)
        {
            node.getNome().apply(this);
        }
        {
            List<TId> copy = new ArrayList<TId>(node.getAcessos());
            Collections.reverse(copy);
            for(TId e : copy)
            {
                e.apply(this);
            }
        }
        outAAtributoExp(node);
    }

    public void inABlocoExp(ABlocoExp node)
    {
        defaultIn(node);
    }

    public void outABlocoExp(ABlocoExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlocoExp(ABlocoExp node)
    {
        inABlocoExp(node);
        if(node.getBlocoExp() != null)
        {
            node.getBlocoExp().apply(this);
        }
        outABlocoExp(node);
    }

    public void inABlocoExpBlocoExp(ABlocoExpBlocoExp node)
    {
        defaultIn(node);
    }

    public void outABlocoExpBlocoExp(ABlocoExpBlocoExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlocoExpBlocoExp(ABlocoExpBlocoExp node)
    {
        inABlocoExpBlocoExp(node);
        if(node.getValor() != null)
        {
            node.getValor().apply(this);
        }
        {
            List<PAtributosAlt> copy = new ArrayList<PAtributosAlt>(node.getAtributos());
            Collections.reverse(copy);
            for(PAtributosAlt e : copy)
            {
                e.apply(this);
            }
        }
        outABlocoExpBlocoExp(node);
    }
}
