/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.parser;

import dplusplus.node.*;
import dplusplus.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTKwFamily(@SuppressWarnings("unused") TKwFamily node)
    {
        this.index = 0;
    }

    @Override
    public void caseTKwDerives(@SuppressWarnings("unused") TKwDerives node)
    {
        this.index = 1;
    }

    @Override
    public void caseTKwFrom(@SuppressWarnings("unused") TKwFrom node)
    {
        this.index = 2;
    }

    @Override
    public void caseTKwStart(@SuppressWarnings("unused") TKwStart node)
    {
        this.index = 3;
    }

    @Override
    public void caseTKwFinish(@SuppressWarnings("unused") TKwFinish node)
    {
        this.index = 4;
    }

    @Override
    public void caseTKwObject(@SuppressWarnings("unused") TKwObject node)
    {
        this.index = 5;
    }

    @Override
    public void caseTKwAlterable(@SuppressWarnings("unused") TKwAlterable node)
    {
        this.index = 6;
    }

    @Override
    public void caseTKwUnalterable(@SuppressWarnings("unused") TKwUnalterable node)
    {
        this.index = 7;
    }

    @Override
    public void caseTKwAnswer(@SuppressWarnings("unused") TKwAnswer node)
    {
        this.index = 8;
    }

    @Override
    public void caseTKwNumber(@SuppressWarnings("unused") TKwNumber node)
    {
        this.index = 9;
    }

    @Override
    public void caseTValorYes(@SuppressWarnings("unused") TValorYes node)
    {
        this.index = 10;
    }

    @Override
    public void caseTValorNo(@SuppressWarnings("unused") TValorNo node)
    {
        this.index = 11;
    }

    @Override
    public void caseTKwProcedure(@SuppressWarnings("unused") TKwProcedure node)
    {
        this.index = 12;
    }

    @Override
    public void caseTKwFunction(@SuppressWarnings("unused") TKwFunction node)
    {
        this.index = 13;
    }

    @Override
    public void caseTKwIn(@SuppressWarnings("unused") TKwIn node)
    {
        this.index = 14;
    }

    @Override
    public void caseTKwCase(@SuppressWarnings("unused") TKwCase node)
    {
        this.index = 15;
    }

    @Override
    public void caseTKwThat(@SuppressWarnings("unused") TKwThat node)
    {
        this.index = 16;
    }

    @Override
    public void caseTKwOtherwise(@SuppressWarnings("unused") TKwOtherwise node)
    {
        this.index = 17;
    }

    @Override
    public void caseTKwAs(@SuppressWarnings("unused") TKwAs node)
    {
        this.index = 18;
    }

    @Override
    public void caseTKwLong(@SuppressWarnings("unused") TKwLong node)
    {
        this.index = 19;
    }

    @Override
    public void caseTKwIf(@SuppressWarnings("unused") TKwIf node)
    {
        this.index = 20;
    }

    @Override
    public void caseTKwElse(@SuppressWarnings("unused") TKwElse node)
    {
        this.index = 21;
    }

    @Override
    public void caseTValorReal(@SuppressWarnings("unused") TValorReal node)
    {
        this.index = 22;
    }

    @Override
    public void caseTValorInteiro(@SuppressWarnings("unused") TValorInteiro node)
    {
        this.index = 23;
    }

    @Override
    public void caseTOpAssign(@SuppressWarnings("unused") TOpAssign node)
    {
        this.index = 24;
    }

    @Override
    public void caseTOpEntry(@SuppressWarnings("unused") TOpEntry node)
    {
        this.index = 25;
    }

    @Override
    public void caseTOpPlus(@SuppressWarnings("unused") TOpPlus node)
    {
        this.index = 26;
    }

    @Override
    public void caseTOpMinus(@SuppressWarnings("unused") TOpMinus node)
    {
        this.index = 27;
    }

    @Override
    public void caseTOpMult(@SuppressWarnings("unused") TOpMult node)
    {
        this.index = 28;
    }

    @Override
    public void caseTOpDiv(@SuppressWarnings("unused") TOpDiv node)
    {
        this.index = 29;
    }

    @Override
    public void caseTOpEq(@SuppressWarnings("unused") TOpEq node)
    {
        this.index = 30;
    }

    @Override
    public void caseTOpLt(@SuppressWarnings("unused") TOpLt node)
    {
        this.index = 31;
    }

    @Override
    public void caseTOpGt(@SuppressWarnings("unused") TOpGt node)
    {
        this.index = 32;
    }

    @Override
    public void caseTOpAnd(@SuppressWarnings("unused") TOpAnd node)
    {
        this.index = 33;
    }

    @Override
    public void caseTOpOr(@SuppressWarnings("unused") TOpOr node)
    {
        this.index = 34;
    }

    @Override
    public void caseTOpNot(@SuppressWarnings("unused") TOpNot node)
    {
        this.index = 35;
    }

    @Override
    public void caseTLBracket(@SuppressWarnings("unused") TLBracket node)
    {
        this.index = 36;
    }

    @Override
    public void caseTRBracket(@SuppressWarnings("unused") TRBracket node)
    {
        this.index = 37;
    }

    @Override
    public void caseTLPar(@SuppressWarnings("unused") TLPar node)
    {
        this.index = 38;
    }

    @Override
    public void caseTRPar(@SuppressWarnings("unused") TRPar node)
    {
        this.index = 39;
    }

    @Override
    public void caseTDot(@SuppressWarnings("unused") TDot node)
    {
        this.index = 40;
    }

    @Override
    public void caseTPipe(@SuppressWarnings("unused") TPipe node)
    {
        this.index = 41;
    }

    @Override
    public void caseTAmp(@SuppressWarnings("unused") TAmp node)
    {
        this.index = 42;
    }

    @Override
    public void caseTSeta(@SuppressWarnings("unused") TSeta node)
    {
        this.index = 43;
    }

    @Override
    public void caseTIdClasse(@SuppressWarnings("unused") TIdClasse node)
    {
        this.index = 44;
    }

    @Override
    public void caseTId(@SuppressWarnings("unused") TId node)
    {
        this.index = 45;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 46;
    }
}
